### ISSUE TITLE
console and setup binaries

### ISSUE THREAD

**Issue by ZeroChaos-** [rapid7/rex-powershell#2]
does this really need to ship the same console and setup binaries as rex-text and rex-random_identifier?

**Comment by bcook-r7** [comment]
hey @dmaloney-r7, any comment?

**Comment by thelightcosine** [comment]
These are automatically generated as part of the gem construction process. AFAICT they're not really important, and I don't think it would hurt anything to remove them

**Comment by bcook-r7** [comment]
They have been removed, thanks @ZeroChaos- . Will work on removing the rest as well.
